### ISSUE TITLE
Add FSRAR resources

### ISSUE THREAD

**Issue by EgorEmeliyanov** [dustinbaer/stop-russian-disinformation#14]
One great attack target is FSRAR -- the Russian federal alcohol sales watchdog agency. The thing is -- each liquor transaction in Russia is logged and transmitted to the agency's servers via Internet using the system called EGAIS (even small retail purchases). Disabling its endpoints would stall alcohol sales in Russia and end the war fairly quickly:

https://balancer.fsrar.ru/
https://utm.egais.ru/
etc.

Issues: a) this target isn't technically a part of the disinformation campaign, but the original website list includes Oauth endpoints of a Russian state-owned bank, so I guess that counts too.
b) they are blocking all foreign traffic fairly quickly, so this might be futile

**Comment by dustinbaer** [comment]
Thanks for your input @EgorEmeliyanov .

Unfortunately, those targets are not part of any disinformation campaign,
so they will not be applied to.
